apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
  namespace: workshop
data:
  BANNER_TEXT: "Hello M2 IR"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: workshop
stringData:
  DB_USER: app
  DB_PASS: changeMe123
