apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: demo
  labels: { app: front }
spec:
  replicas: 1
  selector:
    matchLabels: { app: front }
  template:
    metadata:
      labels: { app: front }
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports: [{ name: http, containerPort: 80 }]
        readinessProbe:
          httpGet: { path: "/", port: 80 }
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet: { path: "/", port: 80 }
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 5
