apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: demo
  labels: { app: front }
spec:
  type: NodePort
  selector: { app: front }
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
