apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-front
  namespace: workshop
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
    traefik.ingress.kubernetes.io/router.middlewares: workshop-strip-front@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts: ["workshop.local"]
    secretName: web-tls
  rules:
  - host: workshop.local
    http:
      paths:
      - path: /front
        pathType: Prefix
        backend:
          service:
            name: front
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-api
  namespace: workshop
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
    traefik.ingress.kubernetes.io/router.middlewares: workshop-strip-api@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts: ["workshop.local"]
    secretName: web-tls
  rules:
  - host: workshop.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 80
