services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: app
    ports:
      - "5432:5432"     # DB (simple pour tester)
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/app
    ports:
      - "3000:3000"     # API (simple pour tester)
    depends_on:
      - db

  front:
    image: nginx:1.27-alpine
    volumes:
      - ./front/dist:/usr/share/nginx/html:ro
    ports:
      - "8080:80"       # FRONT (page statique)

volumes:
  db_data: {}
